version: 2.1
executors:
  generic-executor:
    docker:
      - image: circleci/php:7.2-cli
    working_directory: ~/project
    environment:
      WORKSPACE: "/tmp/workspace"
      LOCAL_BIN: "/tmp/workspace/bin"
      STATEDIR: "/tmp/workspace/state"
      INIT_RC: "/tmp/workspace/state/init.rc"

jobs:

  initialize:
    executor: generic-executor
    steps:
      - checkout

      - run:
          name: "Initialize workspace"
          command: |
              mkdir -p ${STATEDIR} ${LOCAL_BIN}
              bin/didactic-init

      - persist_to_workspace:
          root: .
          paths:
            - bin
            - state

  update:
    executor: generic-executor
    steps:
      - attach_workspace:
          at: .

      - run:
          name: "Read configuration, update didactic-mgr"
          command: |
              . ${INIT_RC}
              didactic-update

      - run:
          name: "Generate documentation"
          command: |
              . ${INIT_RC}
              set +e
              git config --global user.email "sweg-ci@ucar.edu"
              git config --global user.name "NCAR SWEG CI"
              git clone https://${GH_TOKEN}@github.com/${REPO}.wiki.git /tmp/wiki
              ./citools-docgen --bindir=bin /tmp/wiki
              cd /tmp/wiki
              git add .
              git commit -m 'Latest doc build'
              git push

workflows:
  version: 2
  build:
    jobs:
      - initialize:
          filters:
            branches:
              only: master
      - update:
          requires:
            - initialize
          filters:
            branches:
              only: master


